services:
  # === API ===
  - name: mithes-api
    type: web
    env: docker
    plan: free
    rootDir: ./contact-form-backend   # <<< BURASI
    dockerfilePath: ./Dockerfile      # <<< Düzeltildi
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
    healthCheckPath: /actuator/health  # Spring Boot actuator varsa

  # === Frontend ===
  - name: mithes-web
    type: web
    env: docker
    plan: free
    rootDir: ./frontend-2             # <<< BURASI
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: BACKEND_URL
        fromService:
          name: mithes-api
          type: web
          property: hostport
